In [1]:
pip install numpy

  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


NumPy is the core numerical computing library for Python, widely used for:

* Fast array and matrix operations
* Linear algebra
* Random number generation
* Scientific computing
* Data analysis and machine learning foundations



In [6]:
np.__version__

'2.4.6'

In [7]:
lst =list(range(1,20))

In [8]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [9]:
type(lst)

list

In [10]:
arr = np.array(lst)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
lst = [1,23,45,6,78,9,0,6,5,4]
arr =np.array(lst)

In [13]:
type(arr)

numpy.ndarray

In [23]:
arr =np.array([1,2,3,4,5,6,7,5,4,3,2,3,4,5,6,7])

In [18]:
arr =np.array([range(1,20)])

In [19]:
type(arr)

numpy.ndarray

In [20]:
arr =np.arange(1,21)

In [21]:
type(arr)

numpy.ndarray

In [24]:
arr =np.zeros(10)

In [25]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
arr =np.ones(10)

In [27]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
arr =np.zeros((5,10))
arr 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr =np.zeros((5,10))
print(arr.ndim)

2


In [31]:
arr= np.linspace(1,10,5)
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [51]:
arr= np.arange(0,30)


In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
arr = arr.reshape(10,3)

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [54]:
arr = arr.reshape(5,6)

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [56]:
np.random.randint(1,5,10)

array([2, 4, 3, 1, 1, 1, 4, 2, 2, 1], dtype=int32)

In [57]:
arr= np.random.randint(1,5,(5,6))
arr

array([[3, 2, 2, 2, 3, 4],
       [4, 4, 2, 2, 4, 1],
       [3, 4, 4, 2, 4, 1],
       [4, 3, 3, 3, 2, 4],
       [1, 3, 4, 3, 4, 2]], dtype=int32)

In [58]:
np.random.random(10)

array([0.99531218, 0.98174175, 0.92248355, 0.23194672, 0.8960892 ,
       0.03564564, 0.87187065, 0.27120063, 0.17170315, 0.69140414])

In [61]:
# arr= np.random.random(10,3)
# arr


In [64]:
# arr= np.range(60).reshape(12,5)
# arr

In [66]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(5, 6)
int32
30


In [72]:
lst = [[1,2,3,4],[5,7,0,6]]
lst

[[1, 2, 3, 4], [5, 7, 0, 6]]

In [73]:
arr =np.array(lst)

In [74]:
arr

array([[1, 2, 3, 4],
       [5, 7, 0, 6]])

In [75]:
arr =np.arange(60).reshape(6,10)

In [76]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [77]:
print(arr.shape)

(6, 10)


In [78]:
arr.T

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])

In [79]:
arr[0,0]

np.int64(0)

In [80]:
arr[0][0]

np.int64(0)

In [86]:
# arr[11][-1]

In [87]:
arr[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [88]:
arr[2:4,3:]

array([[23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39]])

In [91]:
# arr[9:11]

In [95]:
arr[0:9,3:4]

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53]])

In [96]:
arr[-1,-1]=100

In [97]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58, 100]])

In [98]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(6, 10)
int64
60


In [104]:
arr = np.array([
    [[3, 1, 2],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])



In [105]:
arr

array([[[ 3,  1,  2],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr =np.arange(225).reshape(5,15,3) ##3 layers #15 rows #5 columns

In [112]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [113]:
arr[0][0][0]

np.int64(0)

In [114]:
arr[-1]

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [120]:
arr[1][2][0]

np.int64(51)

In [121]:
arr[0,0,0]


np.int64(0)

In [124]:
arr[0:4,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137]])

In [127]:
# arr[4:0,3]

In [128]:
arr[0:5,0,0]

array([  0,  45,  90, 135, 180])

In [129]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [139]:
arr[0:3,0:3,2:4] 

array([[[ 2],
        [ 5],
        [ 8]],

       [[47],
        [50],
        [53]],

       [[92],
        [95],
        [98]]])

In [141]:
arr[-1,-1,-1]

np.int64(224)

In [146]:
# arr[-1,-1,14]

In [149]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

3
(5, 15, 3)
int64
225


In [150]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [160]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

arr1.sort()

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [159]:
arr1.sort()

In [162]:
print(arr1.sort())

None


In [166]:
arr=np.arange(225)

In [167]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [168]:
arr= arr.reshape(5,15,3)

In [169]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11